### ISSUE TITLE
Build fails when ..disquss:: is added to index.

### ISSUE THREAD

**Issue by gtalarico** [Robpol86/sphinxcontrib-disqus#6]
I have `..disquss::` added to all my pages.
When I add it to the index.rst, the build fails with the traceback is below:

```
Running Sphinx v1.4.8
making output directory...
DOC_DIR: /home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/checkouts/latest/docs
ROOT_DIR: /home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/checkouts/latest
[ERROR] No module named 'clr'
[WARNING] Could not Revit Document. Will Import Sphinx Compat Vars
[CRITICAL] Could Not load Forms dependencies
[WARNING] No module named 'forms'
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocssinglehtmllocalmedia]: all documents
updating environment: 15 added, 0 changed, 0 removed
reading sources... [  6%] base
reading sources... [ 13%] collector
reading sources... [ 20%] dynamo
reading sources... [ 26%] element
reading sources... [ 33%] enumeration
reading sources... [ 40%] exceptions
reading sources... [ 46%] forms
[ERROR] Import Error: No module named 'clr'
reading sources... [ 53%] globals
reading sources... [ 60%] index
reading sources... [ 66%] known_issues
reading sources... [ 73%] revitpythonshell
reading sources... [ 80%] selection
reading sources... [ 86%] tests
reading sources... [ 93%] transaction
reading sources... [100%] utils

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
assembling single document... 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/html.py", line 1050, in write
    doctree = self.assemble_doctree()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/html.py", line 973, in assemble_doctree
    tree = inline_all_toctrees(self, set(), master, tree, darkgreen, [master])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/util/nodes.py", line 245, in inline_all_toctrees
    tree = tree.deepcopy()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1007, in deepcopy
    copy = self.copy()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/util/nodes.py", line 299, in _new_copy
    newnode = self.__class__(self.rawsource, **self.attributes)
TypeError: __init__() got an unexpected keyword argument 'dupnames'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/util/nodes.py", line 299, in _new_copy
    newnode = self.__class__(self.rawsource, **self.attributes)
TypeError: __init__() got an unexpected keyword argument 'dupnames'
The full traceback has been saved in /tmp/sphinx-err-_rlco9qy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug rep
```

**Comment by gtalarico** [comment]
Removed ..disquss:: from index.rst, build passed. Added again, Failed Again
Build always breaks in the same step, but with different keyword args:

```
Running Sphinx v1.5.5
making output directory...
DOC_DIR: /home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/checkouts/latest/docs
ROOT_DIR: /home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/checkouts/latest
[ERROR] No module named 'clr'
[WARNING] Could not Revit Document. Will Import Sphinx Compat Vars
[CRITICAL] Could Not load Forms dependencies
[WARNING] No module named 'forms'
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocssinglehtmllocalmedia]: all documents
updating environment: 15 added, 0 changed, 0 removed
reading sources... [  6%] base
reading sources... [ 13%] collector
reading sources... [ 20%] dynamo
reading sources... [ 26%] element
reading sources... [ 33%] enumeration
reading sources... [ 40%] exceptions
reading sources... [ 46%] forms
[ERROR] Import Error: No module named 'clr'
reading sources... [ 53%] globals
reading sources... [ 60%] index
reading sources... [ 66%] known_issues
reading sources... [ 73%] revitpythonshell
reading sources... [ 80%] selection
reading sources... [ 86%] tests
reading sources... [ 93%] transaction
reading sources... [100%] utils

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
assembling single document... 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/html.py", line 1055, in write
    doctree = self.assemble_doctree()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/builders/html.py", line 978, in assemble_doctree
    tree = inline_all_toctrees(self, set(), master, tree, darkgreen, [master])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/util/nodes.py", line 273, in inline_all_toctrees
    tree = tree.deepcopy()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1008, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/docutils/nodes.py", line 1007, in deepcopy
    copy = self.copy()
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/util/nodes.py", line 348, in _new_copy
    newnode = self.__class__(self.rawsource, **self.attributes)
TypeError: __init__() got an unexpected keyword argument 'names'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/revitpythonwrapper/envs/latest/local/lib/python3.5/site-packages/sphinx/util/nodes.py", line 348, in _new_copy
    newnode = self.__class__(self.rawsource, **self.attributes)
TypeError: __init__() got an unexpected keyword argument 'names'
The full traceback has been saved in /tmp/sphinx-err-ayi1gb5z.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

**Comment by dominicpace** [comment]
I'm experiencing the same bug. I had to remove the ..disquss:: from my index.rst page to fix it. Also tried putting it in an Include but that did not work either.

**Comment by Robpol86** [comment]
Cannot reproduce. Also no longer supporting Python 3.5.

**Comment by eMUQI** [comment]
Encountered the same problem, trying to add comments in the index.rst, readthedoc will report an error during compilation. When I delete the following content in index.rst, everything is normal.

```
.. disqus::
    :disqus_identifier: x-sense-hat-index
```

test on **python 3.8 3.10 3.11** 

```
Running Sphinx v5.3.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [readthedocssinglehtmllocalmedia]: all documents
updating environment: [new config] 27 added, 0 changed, 0 removed
[omitted]
pickling environment... done
checking consistency... done
preparing documents... done
assembling single document... failed

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 307, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 376, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/builders/singlehtml.py", line 149, in write
    doctree = self.assemble_doctree()
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/builders/singlehtml.py", line 71, in assemble_doctree
    tree = inline_all_toctrees(self, set(), master, tree, darkgreen, [master])
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/util/nodes.py", line 415, in inline_all_toctrees
    tree = tree.deepcopy()
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 1093, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 1093, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 1093, in deepcopy
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 1093, in <listcomp>
    copy.extend([child.deepcopy() for child in self.children])
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/docutils/nodes.py", line 1092, in deepcopy
    copy = self.copy()
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/util/nodes.py", line 636, in _new_copy
    newnode = self.__class__(self.rawsource, **self.attributes)
TypeError: __init__() got an unexpected keyword argument 'ids'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/x-sense-hat/envs/latest/lib/python3.8/site-packages/sphinx/util/nodes.py", line 636, in _new_copy
    newnode = self.__class__(self.rawsource, **self.attributes)
TypeError: __init__() got an unexpected keyword argument 'ids'
The full traceback has been saved in /tmp/sphinx-err-c5n_ifi0.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
